name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    uses: Omochice/tataku-share-actions/.github/workflows/generate-doc.yml@4bfe66a422534797cff339976830dd1e187ba1cd # v2.0.16
    permissions:
      contents: write
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.PODENO_APP_ID }}
      PRIVATE_KEY: ${{ secrets.PODENO_PRIVATE_KEY }}
