name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  generate-doc:
    uses: Omochice/tataku-share-actions/.github/workflows/generate-doc.yml@67c3c662abb4d349376a9ab53640f11cd9f679fb # v2.0.15
    permissions:
      contents: write
      pull-requests: write
    secrets:
      APP_ID: ${{ secrets.PODENO_APP_ID }}
      PRIVATE_KEY: ${{ secrets.PODENO_PRIVATE_KEY }}
